server:
  port: 8182

spring:
  #profiles:
  #  active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/emaster?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useSSL=true
    username: root
    password: cyymysql123.

mybatis:
  config-location: "classpath:mybatis/mybatis.config.xml"
  mapper-locations:
    - "classpath:mybatis/mapper/**/*.xml"
  type-aliases-package: com.elling.book.book.sys.**.entity

logging:
  path:
  config: #classpath:config/logback-spring.xml
  level:
    com.elling.book.sys.**.dao.mapper: DEBUG
